[workspace]
members = [
    "pasta6_core",
    "pasta6_home",
    "pasta6_meta",
    "pasta6_paste",
    "pasta6_util",
]

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = true
codegen-units = 1
