[package]
name = "pastaaaaaa"
version = "0.1.0"
authors = ["Nikita Pekin <contact@nikitapek.in>"]
edition = "2018"

[dependencies]
askama = "0.10.3"
askama_warp = "0.10.0"
bytes = "0.5.6"
chrono = "0.4.13"
deadpool-postgres = "0.5.6"
hyper = "0.13.7"
listenfd = "0.3.3"
serde = { version = "1.0.115", features = ["derive"] }
serde_derive = "1.0.115"
tokio = { version = "0.2.22", features = ["macros"] }
tokio-postgres = { version = "0.5.5", features = ["with-chrono-0_4"] }
warp = "0.2.4"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = true
codegen-units = 1
