[package]
name = "pasta6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

monoio = { version = "0.0.3", default-features = false }
monoio-compat = { version = "0.0.4", default-features = false }
hyper = { version = "0.14.16", default-features = false, features = ["http1", "server"]}
rand = { version = "0.8.4", default-features = false, features = ["std", "std_rng"] }
sled = { version = "0.34.6", default-features = false }
