# fly.toml file generated for pasta6 on 2022-01-09T06:58:59-05:00

app = "pasta6"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  # required because fly.io can't infer the binary's name
  cmd = "./pasta6"
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  #[services.concurrency]
  #  hard_limit = 25
  #  soft_limit = 20
  #  type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
