[pasta6]
# Name of the site. Required.
site_name="pasta6"
# Root domain under which the services are served. Required.
domain="p6.rs"
# 256-bit base64-encoded secret key used for encrypting tokens (shared between services). Required.
# Generate with `cargo run --bin pasta6-generate-key`
secret_key=""
# TTL for authentication tokens. Required.
# Tokens with a timestamp more than TTL seconds in the past are treated as expired.
token_ttl=3600 # 1 hour


[services.paste]
# Name of the service. Required.
name="paste.p6.rs"
# Domain paste.p6.rs is being served at. Required.
domain="https://paste.p6.rs"

# Database connection
[services.paste.database]
# Host to connect to. Treated as a hostname.
# Multiple hosts can be specified, separated by commas. Each host will be tried in turn when connecting. Required.
host="localhost"
# Username to authenticate with. Required.
user="paste.p6.rs"
# Password to authenticate with. Required.
password="paste.p6.rs"
# Name of the database to connect to. Defaults to the username. Required.
dbname="paste.p6.rs"
