[package]
name = "pasta6_util"
version = "0.1.0"
authors = ["Nikita Pekin <contact@nikitapek.in>"]
edition = "2018"

[[bin]]
path = "src/bin/generate_key.rs"
name = "pasta6-generate-key"

[dependencies]
base64 = "0.12.3"
sodiumoxide = "0.2.6"